#开启debug
debug: false

############################################################
#
# spring基础配置
#
############################################################
spring:
  devtools: #开发工具配置
    restart: #重启相关配置
      enabled: false #开启热部署
      additional-paths: src/main/java #设置监听目录
      exclude: static/**,public/**,WEB-INF/** #监听排除目录
  #  cache: #缓存配置
  #    type: redis #使用redis
  datasource: #数据库配置
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8&useSSL=false #连接地址
    username: root #用户名
    password: 121837 #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #连接驱动
  #    type: com.alibaba.druid.pool.DruidDataSource #连接池类型
  #    druid: #连接池设置
  #  redis: #Redis配置
  #    host: 127.0.0.1 #ip
  #    port: 6379 #端口号
  #    password:  #密码
  #    database: 1 #设置数据库
  #    timeout: 1000 #连接超时时间（毫秒，0表示永不超时）
  #    lettuce:
  #      pool:
  #        max-active: 100 #连接池最大连接数（负数表示不限制）
  #        max-wait: -1 #连接池最大阻塞等待时间（负数表示不限制）
  #        max-idle: 10 #连接池最大连接
  #        min-idle: 0 #连接池最小连接
  jackson: #json格式配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

############################################################
#
# server配置
#
############################################################
server: #Serverlet相关配置
  port: 8088 #设置端口
  error: #错误配置
    path: /error #设置错误页面
  tomcat: #tomcat配置
    uri-encoding: utf-8 #设置URI编码
    max-threads: 100 #设置线程数

############################################################
#
# mybatis配置
#
############################################################
mybatis: #mybatis
  type-aliases-package: com.cirvor.learn.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#mapper: #通用Mapper配置
#  mappers: tk.mybatis.mapper.common.Mapper
#  not-empty: false
#  identity: MYSQL
#pagehelper: #分页插件配置
#  helper-dialect: mysql
#  reasonable: false #启用则: pageNo<1会返回第一页;pageNo>pages会查询最后一页
#  support-methods-arguments: true
#  params: count=countSql


#############################################################
##
## 日志输出配置 级别分为：ERROR、WARN、INFO、DEBUG、TRACE
##
#############################################################
#logging.path #日志文件路径
logging.file: spring.logs #设置日志文件
logging:
  level:
    root: ERROR #基础日志
    org.springframework.web: ERROR #web日志
    org.mybatis: ERROR #mybatis日志
    com.battcn: ERROR #
  file:
    max-size: 10M #单日志文件大小
    max-history: 5 #日志文件保存天数