spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #是否支持批量上传
      max-file-size: 1048576 #上传文件最大大小
      max-request-size: 10485760 #上传请求最大大小
      file-size-threshold: 0 #文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中
      resolve-lazily: false #判断是否要延迟解析文件
  cache: #缓存配置
    type: redis #使用redis
  jackson: #json格式配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

############################################################
#
# server配置
#
############################################################
server: #Serverlet相关配置
  port: 8088 #设置端口
  error: #错误配置
    path: /error #设置错误页面
  tomcat: #tomcat配置
    uri-encoding: utf-8 #设置URI编码
    max-threads: 100 #设置线程数

############################################################
#
# mybatis配置
#
############################################################
mybatis: #mybatis
  type-aliases-package: com.cirvor.learn.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper: #通用Mapper配置
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL
  safeDelete: true
  safeUpdate: true
  enum-as-simple-type: true
pagehelper: #分页插件配置
  helper-dialect: mysql
  reasonable: false #启用则: pageNo<1会返回第一页;pageNo>pages会查询最后一页
  support-methods-arguments: true
  params: count=countSql